### ISSUE TITLE
[Bug] Crash when put materials in simple band slot of jewelcrafting station

### ISSUE THREAD

**Issue by Boshigiri** [iron431/irons-jewelry#2]
### Observed behaviour

I put iron ingot in the simple band slot, then game crash

### Expected behaviour

pass

### Steps to reproduce

pass

### Server Type

Single Player

### Crashlog

https://mclo.gs/LcNWnTc

### Mod version

irons_jewelry-1.21.1-1.0.3

### Forge version

neoforge-21.1.90

### Other mods

moonlight lib
connector
lithium

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
this strikes me as a connector issue, can this be replicated without connector?

**Comment by Boshigiri** [comment]
I tested other mods and found that conflicted with Item Obliterator. The neoforge version of this mod has not been ported to 1.21 yet, so I can only use the fabric version instead, so this issue does not need to be fixed
